ansiweather update

diff --git a/bin/ansiweather b/bin/ansiweather
--- a/bin/ansiweather
+++ b/bin/ansiweather
@@ -2,11 +2,11 @@
 
 ###############################################################################
 #                                                                             #
-# AnsiWeather 1.01 (c) by Frederic Cambus 2013-2015                           #
+# AnsiWeather 1.02 (c) by Frederic Cambus 2013-2015                           #
 # https://github.com/fcambus/ansiweather                                      #
 #                                                                             #
 # Created: 2013/08/29                                                         #
-# Last Updated: 2015/03/16                                                    #
+# Last Updated: 2015/05/09                                                    #
 #                                                                             #
 # AnsiWeather is released under the BSD 3-Clause license.                     #
 # See LICENSE file for details.                                               #
@@ -19,13 +19,13 @@
 
 LC_NUMERIC=C
 
-config_file=~/.ansiweatherrc
+config_file=${ANSIWEATHERRC:-~/.ansiweatherrc}
 
 function get_config {
 	ret=""
 	if [ -f $config_file ]
 	then
-		ret=$(grep "^$1:" $config_file | awk -F: '{print $2}') 
+		ret=$(grep "^$1:" $config_file | awk -F: '{print $2}')
 	fi
 
 	if [ "X$ret" = "X" ]
@@ -40,27 +40,34 @@ fetch_cmd=$(get_config "fetch_cmd" || echo "curl -s")
 
 
 
-###[ Check if jq is installed ]###############################################
+###[ Check if bc and jq are installed ]#######################################
 
 jqpath="`which jq`"
 if [ "$jqpath" == "" ]
-then 
-	echo -e "\njq binary is not found, please download it from http://stedolan.github.io/jq/ and put it in your PATH"
-	exit 255
-fi 
+then
+	echo "ERROR : Cannot find jq binary"
+	exit
+fi
+
+bcpath="`which bc`"
+if [ "$bcpath" == "" ]
+then
+	echo "ERROR : Cannot find bc binary"
+	exit
+fi
 
 
 
 ###[ Auto-Location Logic ]####################################################
 
-geo_locate_proto=$(get_config "geo_api_proto" || echo "http")
-geo_locate_api=$(get_config "geo_api_url" || echo "www.telize.com/geoip") #geo location service
-geo_locate_api="${geo_locate_proto}://${geo_locate_api}"
+geo_api_proto=$(get_config "geo_api_proto" || echo "http")
+geo_api_url=$(get_config "geo_api_url" || echo "www.telize.com/geoip") #geo location service
+geo_api="${geo_api_proto}://${geo_api_url}"
 
 function auto_locate {
 	ret=""
 
-	geo_data=$($fetch_cmd $geo_locate_api)
+	geo_data=$($fetch_cmd $geo_api)
 
 	city=$(echo $geo_data | jq -r '.city')
 
@@ -341,7 +348,7 @@ function get_icon {
 if [ $forecast != 0 ]
 then
 	output="$background$text $city forecast $text$delimiter "
-	
+
 	i=0
 	while [ $i -lt $forecast ]
 	do
