ansiweather update

diff --git a/bin/ansiweather b/bin/ansiweather
--- a/bin/ansiweather
+++ b/bin/ansiweather
@@ -6,7 +6,7 @@
 # https://github.com/fcambus/ansiweather                                      #
 #                                                                             #
 # Created: 2013/08/29                                                         #
-# Last Updated: 2013/10/30                                                    #
+# Last Updated: 2013/11/02                                                    #
 #                                                                             #
 # AnsiWeather is released under the BSD 3-Clause license.                     #
 # See LICENSE file for details.                                               #
@@ -36,8 +36,49 @@ function get_config {
 	fi
 }
 
+fetch_cmd=$(get_config "fetch_cmd" || echo "curl -s")
+
+
+
+###[ Check if jq is installed ]###############################################
+
+jqpath="`which jq`"
+if [ "$jqpath" == "" ]
+then 
+	echo -e "\njq binary is not found, please download it from http://stedolan.github.io/jq/ and put it in your PATH"
+	exit 255
+fi 
+
+
+
+###[ Auto-Location Logic ]####################################################
+
+geo_locate_api="http://www.telize.com/geoip" #geo location service
+
+function auto_locate {
+	ret=""
+
+	geo_data=$($fetch_cmd $geo_locate_api)
+
+	city=$(echo $geo_data | jq -r '.city')
+
+	country=$(echo $geo_data | jq -r '.country_code')
+
+	ret=$city,$country
+
+	if [ "$ret" == "," ]
+	then
+		return 1
+	else
+		echo $ret
+	fi
+}
+
 # Location : example "Moscow,RU"
-location=$(get_config "location" || echo "Moscow,RU")
+location=$(get_config "location" || auto_locate || echo "Moscow,RU")
+
+# check and replace spaces for curl requests
+location=$( printf "%s\n" "$location" | sed 's/ /%20/g' )
 
 # System of Units : "metric" or "imperial"
 units=$(get_config "units" || echo "metric")
@@ -48,8 +89,11 @@ symbols=$(get_config "symbols" || echo true)
 # Show forecast : How many days, example "5". "0" is standard output
 forecast=$(get_config "forecast" || echo 0)
 
+# Show daylight : "true" or "false"
+daylight=$(get_config "daylight" || echo false)
+
 # Or get config options from command line flags
-while getopts l:u:s:f: option
+while getopts l:u:s:f:d: option
 do
 	case "${option}"
 	in
@@ -57,6 +101,7 @@ do
 		u) units=${OPTARG};;
 		s) symbols=${OPTARG};;
 		f) forecast=${OPTARG};;
+                d) daylight=${OPTARG};;
 	esac
 done
 
@@ -78,7 +123,8 @@ greeting_text=$(get_config "greeting" || echo "Current weather in")
 wind_text=$(get_config "wind" || echo "Wind")
 humidity_text=$(get_config "humidity" || echo "Humidity")
 pressure_text=$(get_config "pressure" || echo "Pressure")
-
+sunrise_text=$(get_config "sunrise" || echo "Sunrise")
+sunset_text=$(get_config "sunset" || echo "Sunset")
 
 
 ###[ Unicode Symbols for icons ]###############################################
@@ -88,33 +134,44 @@ moon=$(get_config "moon" || echo "\033[36m\xe2\x98\xbd")
 clouds=$(get_config "clouds" || echo "\033[37;1m\xe2\x98\x81")
 rain=$(get_config "rain" || echo "\xe2\x98\x94")
 fog=$(get_config "fog" || echo "\033[37;1m\xe2\x96\x92")
+mist=$(get_config "mist" || echo "\033[34m\xe2\x96\x91")
+haze=$(get_config "haze" || echo "\033[33m\xe2\x96\x91")
 snow=$(get_config "snow" || echo "\033[37;1m\xe2\x9d\x84")
 thunderstorm=$(get_config "thunderstorm" || echo "\xe2\x9a\xa1")
 
 
 
-###[ Check if jq is installed ]###############################################
-
-jqpath="`which jq`"
-if [ "$jqpath" == "" ]
-then 
-	echo -e "\njq binary is not found, please download it from http://stedolan.github.io/jq/ and put it in your PATH"
-	exit 255
-fi 
-
-
 ###[ Fetch Weather data ]######################################################
 
-fetch_cmd=$(get_config "fetch_cmd" || echo "curl -s")
 api_cmd=$([[ $forecast != 0 ]] && echo "forecast/daily" || echo "weather")
-weather=$($fetch_cmd "http://api.openweathermap.org/data/2.5/$api_cmd?q=$location\&units=$units")
+weather=$($fetch_cmd "http://api.openweathermap.org/data/2.5/$api_cmd?q=$location&units=$units")
+
+if [ -z "$weather" ]
+then
+	echo "ERROR : Cannot fetch weather data"
+	exit
+fi
+
+status_code=$(echo $weather | jq -r '.cod')
+
+if [ $status_code != 200 ]
+then
+	echo "ERROR : Cannot fetch weather data for the given location"
+	exit
+fi
 
 
 
 ###[ Process Weather data ]####################################################
 
 function epoch_to_date {
-	ret=$(date -j -r $1 +"%a %b %d")
+	if date -j -r $1 +"%a %b %d" > /dev/null 2>&1; then
+		# BSD
+		ret=$(date -j -r $1 +"%a %b %d")
+	else
+		# GNU
+		ret=$(date -d @$1 +"%a %b %d")
+	fi
 	echo $ret
 }
 
@@ -166,6 +223,35 @@ fi
 
 
 
+###[ Process Sunrise and Sunset data ]#########################################
+
+function epoch_to_time {
+	unamestr=$(uname)
+	if date -j -r $1 +"%r" > /dev/null 2>&1; then
+		# BSD
+		ret=$(date -j -r $1 +"%b %d %r")
+	else
+		# GNU
+		ret=$(date -d @$1 +"%b %d %r")
+	fi
+	echo $ret
+}
+
+if [ $forecast = 0 ]
+then
+    if [ -n "$sunrise" ]
+    then
+	sunrise_time=$(epoch_to_time $sunrise)
+    fi
+
+    if [ -n "$sunset" ]
+    then
+	sunset_time=$(epoch_to_time $sunset)
+    fi
+fi
+
+
+
 ###[ Set the period ]##########################################################
 
 now=$(date +%s)
@@ -174,7 +260,10 @@ if [ $forecast != 0 ]
 then
 	period="none"
 else
-	if [ $now -ge $sunset ] || [ $now -le $sunrise ]
+	if [ -z "$sunset" ] || [ -z "$sunrise" ]
+	then
+		period="day"
+	elif [ $now -ge $sunset ] || [ $now -le $sunrise ]
 	then
 		period="night"
 	else
@@ -224,6 +313,12 @@ function get_icon {
 		Fog)
 			echo "$fog "
 			;;
+		Mist)
+			echo "$mist "
+			;;
+		Haze)
+			echo "$haze "
+			;;
 		Snow)
 			echo "$snow "
 			;;
@@ -260,5 +355,14 @@ then
 	output="$output\033[0m"
 	echo -e "$output"
 else
-	echo -e "$background$text $greeting_text $city $delimiter$data $temperature $scale $icon$dashes$text $wind_text $delimiter$data $wind $speed_unit $direction $dashes$text $humidity_text $delimiter$data $humidity % $dashes$text $pressure_text $delimiter$data $pressure $pressure_unit \033[0m"
+        output="$background$text $greeting_text $city $delimiter$data $temperature $scale $icon$dashes$text $wind_text $delimiter$data $wind $speed_unit $direction $dashes$text $humidity_text $delimiter$data $humidity % $dashes$text $pressure_text $delimiter$data $pressure $pressure_unit"
+
+        if [ $daylight = true ]
+        then
+            output="$output $dashes$text $sunrise_text $delimiter$data $sunrise_time $dashes$text $sunset_text $delimiter$data $sunset_time"
+        fi
+
+        output="$output \033[0m"
+
+        echo -e "$output"
 fi
